spring:
  jpa:
    show-sql:true
  data:
    rest:
      base-path: /api

logging:
  file: logs/TacoCloud.log
  level:
    root: WARN
    org.springframework.security: INFO

taco:
  orders:
    pageSize: 10